config/routes.rb
AuthlogicExample::Application.routes.draw do
  resources :users, :except => [:new]
  get '/register', :to => 'users#new', :as => :register

  resource :user_session, :only => [:create]
  get '/login', :to => 'user_sessions#new', :as => :login
  delete '/logout', :to => 'user_sessions#destroy', :as => :logout

  resources :passwords, :only => [:create, :update]
  get '/forgot', :to => 'passwords#new', :as => :forgot
  get '/reset/:id', :to => 'passwords#edit', :as => :reset

  get '/activate/:activation_code', :to => 'activations#edit', :as => :activate
  put '/confirm/:id', :to => 'activations#update', :as => :confirm

  root :to => "users#current"
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_filter :load_user_using_perishable_token, :only => [:edit, :update]
  before_filter :require_no_user
  
  def new
    respond_to do |format|
      format.html # new.html.erb
    end
  end
  
  def create
    @user = User.find_by_email(params[:email])
    respond_to do |format|
      if @user
        @user.deliver_password_reset_instructions!
        format.html { redirect_to(root_url, :notice => "Instructions to reset your password have been emailed to you. Please check your email.") }
      else
        format.html { render :action => :new, :notice => "We're sorry, we could not locate a user with that email address." }
      end
    end
  end
  
  def edit
    respond_to do |format|
      format.html # edit.html.erb
    end
  end

  def update
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]
    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => "Password updated.") }
      else
        render :action => :edit
      end
    end
  end

  private
    def load_user_using_perishable_token
      @user = User.find_using_perishable_token(params[:id])
      unless @user
        redirect_to(forgot_path, :notice => "We're sorry, we could not locate the account. Try copying and pasting the URL from your email into a browser or restart the reset password process.")
      end
    end
end

app/views/password_resets/_form.html.haml
= semantic_form_for @user, :url => password_reset_path do |f| 
  = f.inputs do
    = f.input :password, :label => 'Password', :hint => "#{password_meter()} Please use at least one upper-case, lower-case, digit and special character.".html_safe
    // = render :partial => 'password_meter'
    = f.input :password_confirmation, :label => 'Password confirmation'

  = f.buttons do
    = f.commit_button :reset
= javascript_include_tag 'pwd_meter'
:javascript
  $(document).ready(function() {
    $('#user_password').bind('keyup', function() {
      chkPass(this.value);
    });
  })

app/views/password_resets/new.html.haml
%h1 Forgot Password

%p Fill out the form below and instructions to reset your password will be emailed to you:

= form_tag password_resets_path, :class => 'formtastic' do
  = field_set_tag nil, :class => 'inputs' do
    %ol
      %li{ :class => 'string required', :id => 'email_input' }
        = label_tag :email do
          Email
          %abbr{ :title => 'required' }>*
        = text_field_tag :email, nil, :size => 50

  = field_set_tag nil, :class => 'buttons' do
    %ol
      %li{ :class => 'commit' }
        =submit_tag 'Send', :class => 'submit', :id => 'submit'